### ISSUE TITLE
Final Review of the Final Group Report

### ISSUE THREAD

**Issue by Ghaith-Chrit** [JamesPartsafas/soen342#10]
Any final comments on the last group report before @Chr728 submits it? 

Please check the other issue under sprint 3 to discuss the change management section. This issue is regarding all sections excluding the change management section.

**Comment by Divleen12** [comment]
I have made a few minor changes to the QA section, so please refer to the document for more details. The formatting for the first portion of the document needs to be done. Apart from that, everything looks good!

**Comment by Chr728** [comment]
Waiting some small changes in order to do my final revision and approval

**Comment by XavierKMT** [comment]
After a brief review everything looks good, just waiting on everyone to confirm they've finished their parts.

**Comment by CHADBUCK13** [comment]
I made some minor edits for grammar and readability. I have left a few comments as reminders for the final review. Otherwise, LGTM.

**Comment by Ghaith-Chrit** [comment]
LGTM
