### ISSUE TITLE
Change Management Review

### ISSUE THREAD

**Issue by Ghaith-Chrit** [JamesPartsafas/soen342#11]
Any comment on the change management section in the group report? 

For comments regarding any other section in the final group report, please check the other issues under sprint 3.

**Comment by fullKTRL** [comment]
Read through the change management section, everything looks good.

**Comment by Dinferno-lol** [comment]
I read through it, and other than a minor spelling mistake which I corrected all was well.

**Comment by Ghaith-Chrit** [comment]
LGTM
