### ISSUE TITLE
Decide on UI mockup

### ISSUE THREAD

**Issue by Ghaith-Chrit** [JamesPartsafas/soen342#8]
As part of the project, the application's front end ("CraigsTutors") should be done. However, the application will not have any functional back end. 

This task will act as an epic if needed. 

Note: This task will not be finished during sprint 2.

**Comment by janong24** [comment]
Issue will not be closed and will be carried over to Sprint 3.

**Comment by Ghaith-Chrit** [comment]
@janong24 I believe everything regarding the UI mock-up is finished, is there anything to add or can this issue be closed?

**Comment by janong24** [comment]
Nope, UI is all good. Issue may be closed.

**Comment by Ghaith-Chrit** [comment]
Perfect
